apiVersion: v1
kind: Namespace
metadata:
  name: c2c-java-gradle-docker-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-java-gradle-docker-deployment
  namespace: c2c-java-gradle-docker-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/c2c:80f723960ae0757f67fb553865cd0cbd141a2625

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-java-gradle-docker-label
  name: c2c-java-gradle-docker-service
  namespace: c2c-java-gradle-docker-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---